# -*- coding: utf-8 -*-
"""Cópia de genoma region algorithm

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16tLxKx4rF9_5i8ZrnyvpGmbsFRffjzl8
"""
#Esse script é para calcular a porcentagem de GC nos ranges de onde começa e termina o evento de GC.

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

#Lendo os arquivos
df = pd.read_csv('resultado_final_filtrado.csv', sep = "\t")

# Selecionando as colunas 'start', 'end' e 'seq_event' 
df = df[['start', 'end', 'seq_event']]

#Fazendo o DF
df['seq_event'] = df['seq_event'].str.strip().astype(str)
df['start'] = pd.to_numeric(df['start'], errors='coerce').fillna(0).astype(int)
df['end'] = pd.to_numeric(df['end'], errors='coerce').fillna(0).astype(int)

#Aplicando filtro para pegar eventos de mais que 3 nucleotídeos de GC
filtro = df['seq_event'].apply(len) >= 2

new_df = df[filtro]

#print(new_df)

#Pega valor mínimo da coluna start
min(new_df.start.values)

#Pega valor máximo da coluna end
max(new_df.end.values)

interval = new_df[['start', 'end']].to_numpy()

start = interval[:, 0]
end = interval[:, 1]

from pandas.core.indexers import length_of_indexer
def count(start, end):

  verify = {str(k):0 for k in range(min(start), max(end))}
  keys = verify.keys

  len_ = len(start)

  for i in range(min(start), max(end)):

    for j in range(len_):
      if i >= start[j] and i <= end[j]:

        verify[str(i)] += 1

  return verify

test = count(start, end)

keys = list(test.keys())
values = list(test.values())

total = len(new_df)
print(total)
percent = {key: (value / total) *100 for key, value in test.items()}

df_final = pd.DataFrame({'position': keys, 'count': values})
df_final =  df_final.set_index('position')

df_final.to_csv('Porcentagem GC.csv',sep=';',index=False)

"""# Nova seção"""

#Faz uma imagem

plt.figure(figsize=(20, 6))
plt.bar(list(percent.keys()), list(percent.values()))


plt.xlabel('Nucleotide Gene Region')
plt.ylabel('%GC')


plt.title('Variable Gene Region')

x_ticks = range(0, len(values), 20)
plt.xticks(x_ticks)
plt.show()
